export const demoProducts = [
  {
    id: "obsidian-kitchen-island",
    slug: "obsidian-kitchen-island",
    name: "The Obsidian Kitchen Island",
    collection: "Kitchens",
    collectionName: "The Obsidian Series",
    price: 12450,
    material: "Black Marble & Hand-finished Oak",
    badge: "Bestseller",
    category: "Islands",
    materialTag: "Black Marble",
    img: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=900&q=85",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=85",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=85",
      "https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=900&q=85",
    ],
    description:
      "A monolithic kitchen island balancing sculptural black stone with concealed oak storage and integrated prep space.",
    rating: 4.9,
    reviewCount: 24,
    inStock: true,
    stock: 9,
    lowStockThreshold: 5,
    materials: ["Black Marble", "Granite", "Walnut Wood"],
    finishes: [
      { name: "Midnight", color: "#1a1a1a" },
      { name: "Sandstone", color: "#C9C0B4" },
      { name: "Aged Bronze", color: "#7D4E2C" },
    ],
    specs: [
      { label: "Dimensions", value: "300cm x 110cm x 92cm" },
      { label: "Weight", value: "420 kg" },
      { label: "Origin", value: "Tuscany, Italy" },
      { label: "Certification", value: "FSC Certified Oak Base" },
    ],
    craftText:
      "Each island is cut from premium black stone and finished by hand with FSC-certified oak joinery.",
    relatedIds: ["monolith-island-system", "nordic-oak-cabinetry", "midnight-brass-handles"],
  },
  {
    id: "monolith-island-system",
    slug: "monolith-island-system",
    name: "Monolith Island System",
    collection: "Kitchens",
    collectionName: "The Zenith Collection",
    price: 18400,
    material: "Carrara Marble & Matte Graphite Steel",
    badge: "Limited Edition",
    category: "Islands",
    materialTag: "Carrara Marble",
    img: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=85",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=85",
    ],
    description:
      "A seamless architectural centerpiece integrating Carrara marble, graphite steel, and hidden appliance bays.",
    rating: 4.8,
    reviewCount: 18,
    inStock: true,
    stock: 6,
    lowStockThreshold: 4,
    materials: ["Carrara Marble", "Matte Graphite Steel"],
    finishes: [
      { name: "Graphite", color: "#333333" },
      { name: "White Stone", color: "#f5f5f5" },
    ],
    specs: [
      { label: "Dimensions", value: "280cm x 100cm x 90cm" },
      { label: "Weight", value: "380 kg" },
      { label: "Origin", value: "Carrara, Italy" },
    ],
    craftText:
      "Precision-cut stone meets powder-coated steel for a system designed around daily performance.",
    relatedIds: ["obsidian-kitchen-island", "nordic-oak-cabinetry"],
  },
  {
    id: "nordic-oak-cabinetry",
    slug: "nordic-oak-cabinetry",
    name: "Nordic Oak Cabinetry",
    collection: "Kitchens",
    collectionName: "The Zenith Collection",
    price: 12500,
    material: "Natural Blonde Oak & Brushed Brass",
    badge: null,
    category: "Cabinets",
    materialTag: "Brushed Oak",
    img: "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=85",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=900&q=85",
    ],
    description:
      "Modular blonde oak cabinetry with brass reveal lines and quiet-close hardware.",
    rating: 4.7,
    reviewCount: 31,
    inStock: true,
    stock: 14,
    lowStockThreshold: 6,
    materials: ["Blonde Oak", "Brushed Brass"],
    finishes: [
      { name: "Natural Oak", color: "#c8a36a" },
      { name: "Smoked Oak", color: "#7b6144" },
    ],
    specs: [
      { label: "Module Width", value: "60cm / 90cm / 120cm" },
      { label: "Lead Time", value: "6-8 weeks" },
      { label: "Hardware", value: "Soft-close brass system" },
    ],
    craftText:
      "Built from continuous-grain oak panels and assembled with hidden European hinges.",
    relatedIds: ["midnight-brass-handles", "minimalist-oak-island"],
  },
  {
    id: "midnight-brass-galley",
    slug: "midnight-brass-galley",
    name: "Midnight Brass Galley",
    collection: "Kitchens",
    collectionName: "The Zenith Collection",
    price: 21000,
    material: "Deep Navy Enamel & Polished Brass",
    badge: "New Arrival",
    category: "Cabinets",
    materialTag: "Brushed Brass",
    img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=900&q=85",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=900&q=85",
    ],
    description:
      "A dramatic galley program pairing navy lacquered faces with polished brass trim and full-height storage.",
    rating: 4.8,
    reviewCount: 12,
    inStock: true,
    stock: 5,
    lowStockThreshold: 4,
    materials: ["Navy Enamel", "Polished Brass"],
    finishes: [
      { name: "Midnight Navy", color: "#152238" },
      { name: "Antique Brass", color: "#a67c3d" },
    ],
    specs: [
      { label: "Configuration", value: "Galley / L-shape" },
      { label: "Lead Time", value: "8-10 weeks" },
      { label: "Finish", value: "Hand-polished brass" },
    ],
    craftText:
      "Layered enamel and brass detailing create a kitchen system with gallery-level presence.",
    relatedIds: ["midnight-brass-handles", "obsidian-kitchen-island"],
  },
  {
    id: "eames-inspired-lounge",
    slug: "eames-inspired-lounge",
    name: "Eames-inspired Lounge",
    collection: "Complements",
    collectionName: "Iconic Pieces",
    price: 3450,
    material: "Walnut & Obsidian Leather",
    badge: "Client Favorite",
    category: "Seating",
    materialTag: "Walnut",
    img: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85",
    ],
    description:
      "A lounge chair and ottoman silhouette inspired by mid-century comfort, finished in walnut and dark leather.",
    rating: 4.9,
    reviewCount: 42,
    inStock: true,
    stock: 11,
    lowStockThreshold: 5,
    materials: ["Walnut", "Leather"],
    finishes: [
      { name: "Obsidian Leather", color: "#111111" },
      { name: "Cognac Leather", color: "#8b4f2f" },
    ],
    specs: [
      { label: "Frame", value: "Molded walnut veneer" },
      { label: "Upholstery", value: "Top-grain leather" },
      { label: "Warranty", value: "5 years" },
    ],
    craftText:
      "Molded veneer shells and deep upholstery bring timeless lounge comfort to contemporary interiors.",
    relatedIds: ["bronze-geometric-table"],
  },
  {
    id: "minimalist-oak-island",
    slug: "minimalist-oak-island",
    name: "Minimalist Oak Island",
    collection: "Kitchens",
    collectionName: "Nord House",
    price: 2800,
    material: "Solid European Oak",
    badge: null,
    category: "Islands",
    materialTag: "Brushed Oak",
    img: "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1556909212-d5b604d0c90d?w=900&q=85",
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=85",
    ],
    description:
      "A compact oak island designed for apartments, studio kitchens, and flexible hospitality suites.",
    rating: 4.6,
    reviewCount: 15,
    inStock: true,
    stock: 18,
    lowStockThreshold: 6,
    materials: ["European Oak"],
    finishes: [
      { name: "Natural", color: "#c79f62" },
      { name: "Charcoal Oil", color: "#34312c" },
    ],
    specs: [
      { label: "Dimensions", value: "180cm x 80cm x 91cm" },
      { label: "Storage", value: "Two deep drawers" },
      { label: "Lead Time", value: "3-4 weeks" },
    ],
    craftText:
      "Solid oak boards are matched for grain continuity and finished with a low-VOC hardwax oil.",
    relatedIds: ["nordic-oak-cabinetry", "midnight-brass-handles"],
  },
  {
    id: "bronze-geometric-table",
    slug: "bronze-geometric-table",
    name: "Bronze Geometric Table",
    collection: "Complements",
    collectionName: "Sculptural Accents",
    price: 4100,
    material: "Tinted Glass & Bronze",
    badge: null,
    category: "Tables",
    materialTag: "Bronze",
    img: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85",
      "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=900&q=85",
    ],
    description:
      "A faceted bronze base supports low-iron tinted glass for dining rooms and statement lounges.",
    rating: 4.7,
    reviewCount: 19,
    inStock: true,
    stock: 7,
    lowStockThreshold: 4,
    materials: ["Bronze", "Tinted Glass"],
    finishes: [
      { name: "Burnished Bronze", color: "#8c6239" },
      { name: "Smoke Glass", color: "#6f7476" },
    ],
    specs: [
      { label: "Seats", value: "6-8" },
      { label: "Glass", value: "12mm tempered" },
      { label: "Base", value: "Patinated bronze" },
    ],
    craftText:
      "The bronze base is hand-patinated in small batches, giving each table subtle tonal variation.",
    relatedIds: ["eames-inspired-lounge"],
  },
  {
    id: "midnight-brass-handles",
    slug: "midnight-brass-handles",
    name: "Midnight Brass Handles",
    collection: "Complements",
    collectionName: "Hardware Atelier",
    price: 320,
    material: "Blackened Brass",
    badge: "Low Stock",
    category: "Hardware",
    materialTag: "Brass",
    img: "https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=700&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228841-a3c527ebefe5?w=900&q=85",
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=900&q=85",
    ],
    description:
      "A set of hand-finished cabinet pulls in blackened brass for kitchens, wardrobes, and built-ins.",
    rating: 4.8,
    reviewCount: 27,
    inStock: true,
    stock: 4,
    lowStockThreshold: 8,
    materials: ["Blackened Brass"],
    finishes: [
      { name: "Midnight Brass", color: "#3a3128" },
      { name: "Raw Brass", color: "#b08d57" },
    ],
    specs: [
      { label: "Set", value: "8 handles" },
      { label: "Length", value: "18cm" },
      { label: "Mounting", value: "Included" },
    ],
    craftText:
      "Hand-burnished brass hardware designed to add weight and precision to cabinetry details.",
    relatedIds: ["nordic-oak-cabinetry", "midnight-brass-galley"],
  },
];

export const demoCollections = [
  {
    id: "kitchens",
    slug: "kitchens",
    name: "Kitchens",
    description: "Culinary sanctuaries designed around craft and entertaining.",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=900&q=80",
  },
  {
    id: "bedrooms",
    slug: "bedrooms",
    name: "Bedrooms",
    description: "Quiet spaces with tailored storage, beds, and warm finishes.",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=80",
  },
  {
    id: "outdoor",
    slug: "outdoor",
    name: "Outdoor",
    description: "Weather-ready pieces for terraces, gardens, and hospitality patios.",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=80",
  },
  {
    id: "complements",
    slug: "complements",
    name: "Complements",
    description: "Lighting, hardware, seating, and sculptural accents.",
    image: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=900&q=80",
  },
];

export const demoCustomers = [
  {
    id: "cust-eleanor-vance",
    name: "Eleanor Vance",
    email: "eleanor.vance@example.com",
    phone: "+1 (415) 555-0198",
    location: "San Francisco, CA",
    totalSpent: 38200,
    orders: 3,
    status: "VIP",
  },
  {
    id: "cust-julian-thorne",
    name: "Julian Thorne",
    email: "julian.thorne@example.com",
    phone: "+44 20 7946 0958",
    location: "London, UK",
    totalSpent: 18400,
    orders: 1,
    status: "Active",
  },
  {
    id: "cust-maya-rodriguez",
    name: "Maya Rodriguez",
    email: "maya.rodriguez@example.com",
    phone: "+34 600 555 143",
    location: "Barcelona, ES",
    totalSpent: 15720,
    orders: 2,
    status: "Active",
  },
];

export const demoEmployees = [
  {
    id: "emp-marcus-tan",
    _id: "emp-marcus-tan",
    name: "Marcus Tan",
    email: "marcus.tan@hedj.example",
    role: "admin",
    department: "Operations",
  },
  {
    id: "emp-sarah-li",
    _id: "emp-sarah-li",
    name: "Sarah Li",
    email: "sarah.li@hedj.example",
    role: "readonly",
    department: "Design",
  },
  {
    id: "emp-julianne-voss",
    _id: "emp-julianne-voss",
    name: "Julianne Voss",
    email: "julianne.voss@hedj.example",
    role: "readonly",
    department: "Logistics",
  },
];

export const demoLeads = [
  {
    id: "lead-studio-arches",
    name: "Studio Arches",
    contact: "Nora Blake",
    email: "nora@studioarches.example",
    project: "Custom Dining Suite",
    budget: 52000,
    source: "Showroom",
    status: "qualified",
    createdAt: "2026-05-08T10:15:00.000Z",
  },
  {
    id: "lead-maya-rodriguez",
    name: "Maya Rodriguez",
    contact: "Maya Rodriguez",
    email: "maya.rodriguez@example.com",
    project: "Barcelona apartment kitchen refresh",
    budget: 18000,
    source: "Website",
    status: "new",
    createdAt: "2026-05-10T14:25:00.000Z",
  },
];

export const demoQuotes = [
  {
    id: "quote-studio-arches",
    leadId: "lead-studio-arches",
    customerName: "Studio Arches",
    project: "Custom Dining Suite",
    amount: 52000,
    status: "sent",
    items: ["Bronze Geometric Table", "Eames-inspired Lounge"],
    createdAt: "2026-05-09T09:20:00.000Z",
  },
  {
    id: "quote-eleanor-vance",
    leadId: null,
    customerName: "Eleanor Vance",
    project: "Obsidian kitchen island and hardware package",
    amount: 12770,
    status: "approved",
    items: ["The Obsidian Kitchen Island", "Midnight Brass Handles"],
    createdAt: "2026-05-07T16:30:00.000Z",
  },
];

export const demoOrders = [
  {
    id: "HJ-9402",
    customerId: "cust-eleanor-vance",
    customerName: "Eleanor Vance",
    customer: {
      name: "Eleanor Vance",
      email: "eleanor.vance@example.com",
      phone: "+1 (415) 555-0198",
      city: "San Francisco",
      street: "18 Pacific Heights",
    },
    amount: 12450,
    total: 13921,
    status: "production",
    itemsSummary: "The Obsidian Kitchen Island",
    items: [
      { productId: "obsidian-kitchen-island", name: "The Obsidian Kitchen Island", quantity: 1, price: 12450 },
    ],
    assignee: "Marcus Tan",
    progress: 65,
    createdAt: "2026-05-01T11:15:00.000Z",
  },
  {
    id: "HJ-9401",
    customerId: "cust-julian-thorne",
    customerName: "Julian Thorne",
    customer: {
      name: "Julian Thorne",
      email: "julian.thorne@example.com",
      phone: "+44 20 7946 0958",
      city: "London",
      street: "42 Holland Park",
    },
    amount: 18400,
    total: 20359,
    status: "confirmed",
    itemsSummary: "Monolith Island System",
    items: [
      { productId: "monolith-island-system", name: "Monolith Island System", quantity: 1, price: 18400 },
    ],
    assignee: "Julianne Voss",
    depositPaid: true,
    createdAt: "2026-05-03T09:45:00.000Z",
  },
  {
    id: "HJ-9399",
    customerId: "cust-maya-rodriguez",
    customerName: "Maya Rodriguez",
    customer: {
      name: "Maya Rodriguez",
      email: "maya.rodriguez@example.com",
      phone: "+34 600 555 143",
      city: "Barcelona",
      street: "7 Carrer de Mallorca",
    },
    amount: 15720,
    total: 17460,
    status: "ready",
    itemsSummary: "Nordic Oak Cabinetry, Midnight Brass Handles",
    items: [
      { productId: "nordic-oak-cabinetry", name: "Nordic Oak Cabinetry", quantity: 1, price: 12500 },
      { productId: "midnight-brass-handles", name: "Midnight Brass Handles", quantity: 10, price: 320 },
    ],
    assignee: "Sarah Li",
    warehouse: "B-04",
    createdAt: "2026-04-28T13:00:00.000Z",
  },
];

export const demoNotifications = [
  {
    id: "notif-low-stock",
    type: "error",
    tag: "Low Stock Alert",
    name: "Midnight Brass Handles",
    desc: "Only 4 units remaining in main warehouse.",
    action: "Reorder Now",
    createdAt: "2026-05-11T08:30:00.000Z",
  },
  {
    id: "notif-new-quote",
    type: "gold",
    tag: "New Quote Request",
    name: "Custom Dining Suite",
    desc: "Inquiry from Studio Arches regarding bulk pricing.",
    time: "2 hours ago",
    createdAt: "2026-05-11T10:30:00.000Z",
  },
  {
    id: "notif-collection",
    type: "gold",
    tag: "New Collection Launch",
    name: "Nord House",
    desc: "Minimalist Oak Island is now live in Kitchens.",
    createdAt: "2026-05-09T12:00:00.000Z",
  },
];

export const createInitialDemoStore = () => ({
  products: demoProducts,
  collections: demoCollections,
  customers: demoCustomers,
  employees: demoEmployees,
  leads: demoLeads,
  quotes: demoQuotes,
  orders: demoOrders,
  notifications: demoNotifications,
});
